version: "3.8"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    container_name: redis
    hostname: redis
    image: redis:7.0
    restart: unless-stopped
    expose:
      - 6379

  api:
    container_name: api
    hostname: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: api.Dockerfile
    entrypoint: /app/entrypoints/server_entrypoint.sh
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    depends_on:
      - postgres
      - redis

  worker:
    container_name: worker
    hostname: worker
    build:
      context: .
      dockerfile: api.Dockerfile
    entrypoint: /app/entrypoints/worker_entrypoint.sh
    volumes:
      - static_volume:/app/static
    depends_on:
      - postgres
      - redis
      - api

  nginx:
    container_name: nginx
    hostname: nginx
    restart: always
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static

volumes:
  static_volume: {}
  postgres_data: {}
